### ISSUE TITLE
Documentaion bug with mongo properties

### ISSUE THREAD

**Issue by rsobies** [AxonFramework/extension-mongo#486]
### Basic information

I found in the documentation set of properties

```
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  mongo:
    database-name: axon
    token-store:
      enabled: true
    saga-store:
      enabled: false
    event-store:
      enabled: false
```

shouldn't be like this? (missing `axon:`)

```
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
axon:
  mongo:
    database-name: axon
    token-store:
      enabled: true
    saga-store:
      enabled: false
    event-store:
      enabled: false
```
